[template]
prefix = "/service/postgres-cluster"
src = "haproxy.tmpl"
dest = "/etc/haproxy/haproxy.cfg"
check_cmd = "/usr/sbin/haproxy -c -f {{ .src }}"
reload_cmd = "/bin/systemctl reload haproxy"

keys = [
    "/members/",
]
