---

- name: Check if ufw package is installed (on Ubuntu).
  command: service ufw status
  args:
    warn: false
  register: ufw_installed
  failed_when: false
  changed_when: false
  when:
    - firewall_disable_ufw
  check_mode: false

- name: Disable the ufw firewall (on Ubuntu, if configured).
  service:
    name: ufw
    state: stopped
    enabled: false
  when:
    - firewall_disable_ufw
    - ufw_installed.rc == 0

...
