---
# yamllint disable rule:line-length

- name: Create the user/password lookup function for user pgbouncer
  postgresql_query:
    db: "{{ item }}"
    query: |
        CREATE SCHEMA IF NOT EXISTS pgbouncer AUTHORIZATION {{ pgbouncer_user }};
        CREATE OR REPLACE FUNCTION pgbouncer.get_auth(p_usename TEXT)
        RETURNS TABLE(username TEXT, password TEXT) AS
        $$
        BEGIN
            RAISE WARNING 'PgBouncer auth request: %', p_usename;
            RETURN QUERY
            SELECT usename::TEXT, passwd::TEXT FROM pg_catalog.pg_shadow
             WHERE usename = p_usename;
        END;
        $$ LANGUAGE plpgsql SECURITY DEFINER;
        REVOKE ALL ON FUNCTION pgbouncer.get_auth(p_usename TEXT) FROM PUBLIC;
        GRANT EXECUTE ON FUNCTION pgbouncer.get_auth(p_usename TEXT) TO {{ pgbouncer_user }};
    autocommit: yes
  loop: 
    - template1
    - postgres
  ignore_errors: true

...
