---
# yamllint disable rule:line-length

- name: PostgreSQL High-Availability Cluster Scaling (add replica node)
  hosts: replica
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true
  vars_files:
    - vars/main.yml
    - vars/system.yml

  roles:
    - role: common
    - role: ansible-role-firewall
      environment: "{{ proxy_env | default({}) }}"
      vars:
        firewall_allowed_tcp_ports: "{{ firewall_ports_dynamic_var|list | unique }}"
        firewall_additional_rules: "{{ firewall_rules_dynamic_var|list | unique }}"
      when: firewall_enabled_at_boot|bool

    - role: hostname
    - role: resolv_conf
    - role: etc_hosts
    - role: add-repository
    - role: packages
    - role: sudo
    - role: sysctl
    - role: locales
    - role: timezone
    - role: ssh-keys

- hosts: pgbackrest:postgres_cluster
  become: true
  become_method: sudo
  gather_facts: true
  any_errors_fatal: true
  vars_files:
    - vars/main.yml

  roles:
    - role: pgbackrest
      when: pgbackrest_install|bool

- hosts: replica
  become: true
  become_method: sudo
  gather_facts: true
  any_errors_fatal: true
  vars_files:
    - vars/main.yml
    - vars/system.yml
  vars:
    existing_pgcluster: true

  roles:
    - role: pgbouncer
      when: pgbouncer_install|bool

    - role: patroni

    # finish (info)
    - role: deploy-finish

...
